version: '3'

services:

  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"

  backend:
    build: ./backend/
    ports:
      - '6200:6200'
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
      
  frontend:
    build: ./frontend/
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
